#예약이 취소된 경우를 포함시켜야 하나 문제 출제자는 취소된 경우를 포함시키지 않았기 때문에 아래 코드가 정답이 됨
SELECT MCDP_CD as '진료과 코드', COUNT(APNT_NO) as '5월예약건수'
FROM APPOINTMENT
WHERE APNT_YMD LIKE '2022-05-%'
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO), MCDP_CD 

#예약이 취소된 경우를 포함시킬 경우
SELECT MCDP_CD as '진료과 코드', COUNT(APNT_NO) as '5월예약건수'
FROM APPOINTMENT
WHERE APNT_YMD LIKE '2022-05-%' AND APNT_CNCL_YN = 'N'
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO), MCDP_CD 