#가격이 제일 비싼 식품의 정보 출력하기
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM (
    SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE,
       RANK() OVER(ORDER BY PRICE DESC) AS rnk
    FROM FOOD_PRODUCT
    ) as ranked_food
WHERE rnk = 1