# 2022년 1월의 카테고리 별 도서 판매량을 합산
# 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
# 카테고리명 기준으로 오름차순 정렬

SELECT b.CATEGORY, SUM(bs.SALES) as TOTAL_SALES
FROM BOOK b, BOOK_SALES bs
WHERE b.BOOK_ID = bs.BOOK_ID AND
      bs.SALES_DATE LIKE '2022-01-%'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY