# 대장균 개체의 크기를 내름차순으로 정렬했을 때
# 상위 0% ~ 25% 를 'CRITICAL', 26% ~ 50% 를 'HIGH', 51% ~ 75% 를 'MEDIUM', 76% ~ 100% 를 'LOW' 라고 분류하여 조회
# ID 오름차순 정렬하여 조회

SELECT 
    ID, 
    CASE WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.25 THEN 'CRITICAL'
         WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) > 0.25 AND
              PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.5 THEN 'HIGH'
         WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) > 0.5 AND
              PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.75 THEN 'MEDIUM'
         WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) > 0.75 THEN 'LOW'
    END as COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID 